---

num_hosts: 128
num_tors: 1
num_aggr: 0
host_placement: "manual"
leaf_link_speed_gbps: 100
core_link_speed_gbps: 100

hosts:
  0: &host
    tor: 0
    client: true
    server: true
  1: *host
  2: *host
  3: *host
  4: *host
  5: *host
  6: *host
  7: *host
  8: *host
  9: *host
  10: *host
  11: *host
  12: *host
  13: *host
  14: *host
  15: *host
  16: *host
  17: *host
  18: *host
  19: *host
  20: *host
  21: *host
  22: *host
  23: *host
  24: *host
  25: *host
  26: *host
  27: *host
  28: *host
  29: *host
  30: *host
  31: *host
  32: *host
  33: *host
  34: *host
  35: *host
  36: *host
  37: *host
  38: *host
  39: *host
  40: *host
  41: *host
  42: *host
  43: *host
  44: *host
  45: *host
  46: *host
  47: *host
  48: *host
  49: *host
  50: *host
  51: *host
  52: *host
  53: *host
  54: *host
  55: *host
  56: *host
  57: *host
  58: *host
  59: *host
  60: *host
  61: *host
  62: *host
  63: *host
  64: *host
  65: *host
  66: *host
  67: *host
  68: *host
  69: *host
  70: *host
  71: *host
  72: *host
  73: *host
  74: *host
  75: *host
  76: *host
  77: *host
  78: *host
  79: *host
  80: *host
  81: *host
  82: *host
  83: *host
  84: *host
  85: *host
  86: *host
  87: *host
  88: *host
  89: *host
  90: *host
  91: *host
  92: *host
  93: *host
  94: *host
  95: *host
  96: *host
  97: *host
  98: *host
  99: *host
  100: *host
  101: *host
  102: *host
  103: *host
  104: *host
  105: *host
  106: *host
  107: *host
  108: *host
  109: *host
  110: *host
  111: *host
  112: *host
  113: *host
  114: *host
  115: *host
  116: *host
  117: *host
  118: *host
  119: *host
  120: *host
  121: *host
  122: *host
  123: *host
  124: *host
  125: *host
  126: *host
  127: *host
