---

num_hosts: 4
num_tors: 1
num_aggr: 4
host_placement: "manual"
leaf_link_speed_gbps: 100
core_link_speed_gbps: 100

hosts:
  0: &host
    tor: 0
    client: true
    server: true
  1: *host
  2: *host
  3: *host
