---

num_hosts: 144
num_tors: 9
num_aggr: 4
host_placement: "uniform"
leaf_link_speed_gbps: 100
core_link_speed_gbps: 400

hosts:
  0: &tor0
    tor: 0
    client: true
    server: true
  1: *tor0
  2: *tor0
  3: *tor0
  4: *tor0
  5: *tor0
  6: *tor0
  7: *tor0
  8: *tor0
  9: *tor0
  10: *tor0
  11: *tor0
  12: *tor0
  13: *tor0
  14: *tor0
  15: *tor0
  16: &tor1
    tor: 1
    client: true
    server: true
  17: *tor1
  18: *tor1
  19: *tor1
  20: *tor1
  21: *tor1
  22: *tor1
  23: *tor1
  24: *tor1
  25: *tor1
  26: *tor1
  27: *tor1
  28: *tor1
  29: *tor1
  30: *tor1
  31: *tor1
  32: &tor2
    tor: 2
    client: true
    server: true
  33: *tor2
  34: *tor2
  35: *tor2
  36: *tor2
  37: *tor2
  38: *tor2
  39: *tor2
  40: *tor2
  41: *tor2
  42: *tor2
  43: *tor2
  44: *tor2
  45: *tor2
  46: *tor2
  47: *tor2
  48: &tor3
    tor: 3
    client: true
    server: true
  49: *tor3
  50: *tor3
  51: *tor3
  52: *tor3
  53: *tor3
  54: *tor3
  55: *tor3
  56: *tor3
  57: *tor3
  58: *tor3
  59: *tor3
  60: *tor3
  61: *tor3
  62: *tor3
  63: *tor3
  64: &tor4
    tor: 4
    client: true
    server: true
  65: *tor4
  66: *tor4
  67: *tor4
  68: *tor4
  69: *tor4
  70: *tor4
  71: *tor4
  72: *tor4
  73: *tor4
  74: *tor4
  75: *tor4
  76: *tor4
  77: *tor4
  78: *tor4
  79: *tor4
  80: &tor5
    tor: 5
    client: true
    server: true
  81: *tor5
  82: *tor5
  83: *tor5
  84: *tor5
  85: *tor5
  86: *tor5
  87: *tor5
  88: *tor5
  89: *tor5
  90: *tor5
  91: *tor5
  92: *tor5
  93: *tor5
  94: *tor5
  95: *tor5
  96: &tor6
    tor: 6
    client: true
    server: true
  97: *tor6
  98: *tor6
  99: *tor6
  100: *tor6
  101: *tor6
  102: *tor6
  103: *tor6
  104: *tor6
  105: *tor6
  106: *tor6
  107: *tor6
  108: *tor6
  109: *tor6
  110: *tor6
  111: *tor6
  112: &tor7
    tor: 7
    client: true
    server: true
  113: *tor7
  114: *tor7
  115: *tor7
  116: *tor7
  117: *tor7
  118: *tor7
  119: *tor7
  120: *tor7
  121: *tor7
  122: *tor7
  123: *tor7
  124: *tor7
  125: *tor7
  126: *tor7
  127: *tor7
  128: &tor8
    tor: 8
    client: true
    server: true
  129: *tor8
  130: *tor8
  131: *tor8
  132: *tor8
  133: *tor8
  134: *tor8
  135: *tor8
  136: *tor8
  137: *tor8
  138: *tor8
  139: *tor8
  140: *tor8
  141: *tor8
  142: *tor8
  143: *tor8
